name: Test Commit Notification to Discord

on:
  push:
    branches:
      - main  # Adjust this to your desired branch

permissions:
  contents: read  # Read access to repository contents

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire history is fetched

      - name: Get Commit Details
        id: commit_details
        run: |
          # Retrieve commit message and author
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          
          # Debugging: Print the commit message and author to the workflow logs
          echo "Commit Message: $COMMIT_MESSAGE"
          echo "Commit Author: $COMMIT_AUTHOR"
          
          # Set output variables for commit message and author
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"
          echo "::set-output name=commit_author::$COMMIT_AUTHOR"

      - name: Send commit details to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"New commit in ${{ github.repository }} by ${{ steps.commit_details.outputs.commit_author }}: \nCommit message: ${{ steps.commit_details.outputs.commit_message }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
