name: Send Commit Notifications to Discord

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send commit message to Discord
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"New commit in ${{ github.repository }}: $COMMIT_MESSAGE\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
